name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch
    paths:
      - "index.html"  # Only trigger when index.html changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Directory containing index.html (relative to repo root)
          publish_branch: gh-pages
