name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "/Users/artijadhav/Knolens/devops/gh-deployment-workflow/index.html"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

     - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "/Users/artijadhav/Knolens/devops/gh-deployment-workflow/index.html"  # Directory containing index.html
          publish_branch: gh-pages
